import _ from 'lodash';
import './style.css';
// import Data from './data.xml';
// import Notes from './data.csv';
import Skeleton from './mainBody';
import submitBtn from './functionality';
import { retrieve } from './folder';
document.body.appendChild(Skeleton());
console.log(submitBtn());
retrieve();